import * as path from 'path';
import type { AssetMetadata } from '../types';
import { writeFileContent, normalizePath, getRelativePath } from './utils';
import { scanAssetsDirectory } from './scanner';
import type { ScanResult } from './scanner';
import { validateAssets } from './validator';

export interface GenerateOptions {
  assetsDir: string;
  outputDir: string;
  format: 'typescript' | 'javascript';
  baseDir?: string;
}

export interface GenerateResult {
  success: boolean;
  assetsCount: number;
  errors: string[];
  warnings: string[];
  outputPath: string;
}

export function generateAssetRegistry(
  options: GenerateOptions
): GenerateResult {
  const { assetsDir, outputDir, format, baseDir = process.cwd() } = options;

  const scanResult: ScanResult = scanAssetsDirectory(assetsDir, baseDir);

  if (scanResult.errors.length > 0) {
    return {
      success: false,
      assetsCount: 0,
      errors: scanResult.errors,
      warnings: [],
      outputPath: '',
    };
  }

  const validationResult = validateAssets(scanResult.assets);

  const assetNames = scanResult.assets.map((asset) => asset.name);
  const uniqueNames = Array.from(new Set(assetNames));

  const outputPath = path.join(outputDir, 'index.ts');
  const content = generateRegistryContent(
    scanResult.assets,
    assetsDir,
    outputDir,
    format,
    baseDir
  );

  writeFileContent(outputPath, content);

  return {
    success: true,
    assetsCount: uniqueNames.length,
    errors: validationResult.errors,
    warnings: validationResult.warnings,
    outputPath,
  };
}

function ensureRelativePathPrefix(filePath: string): string {
  if (filePath.startsWith('./') || filePath.startsWith('../')) {
    return filePath;
  }
  return `./${filePath}`;
}

function generateRegistryContent(
  assets: AssetMetadata[],
  _assetsDir: string,
  outputDir: string,
  _format: 'typescript' | 'javascript',
  _baseDir: string
): string {
  const assetNames = assets.map((asset) => {
    return `'${asset.name}'`;
  });

  const uniqueAssetNames = Array.from(new Set(assetNames));
  const typeDefinition = `export type AssetName = ${uniqueAssetNames.join(
    ' | '
  )};`;

  const assetImports = assets.map((asset) => {
    const relativePath = getRelativePath(outputDir, asset.path);
    const normalizedPath = normalizePath(relativePath);
    const requirePath = ensureRelativePathPrefix(normalizedPath);
    return `  '${asset.name}': require('${requirePath}'),`;
  });

  const registryContent = `export const ASSETS = {\n${assetImports.join(
    '\n'
  )}\n} as const;`;

  const metadataContent = generateMetadataContent(assets);

  return `// Auto-generated file - do not edit manually
// Generated by react-native-smart-assets

${typeDefinition}

${registryContent}

${metadataContent}

export function getAsset(name: AssetName): typeof ASSETS[AssetName] {
  return ASSETS[name];
}

export function hasAsset(name: string): name is AssetName {
  return name in ASSETS;
}

export function getAllAssetNames(): AssetName[] {
  return Object.keys(ASSETS) as AssetName[];
}
`;
}

interface AssetMetadataRecord {
  name: string;
  type: 'image' | 'svg' | 'icon';
  category: 'images' | 'icons' | 'assets';
  variants?: string[];
  dimensions?: { width: number; height: number };
}

function generateMetadataContent(assets: AssetMetadata[]): string {
  const metadataEntries = assets.map((asset) => {
    const metadata: AssetMetadataRecord = {
      name: asset.name,
      type: asset.type,
      category: asset.category,
    };

    if (asset.variants && asset.variants.length > 0) {
      metadata.variants = asset.variants;
    }

    if (asset.dimensions) {
      metadata.dimensions = asset.dimensions;
    }

    return `  '${asset.name}': ${JSON.stringify(metadata, null, 2)},`;
  });

  return `export const ASSET_METADATA = {\n${metadataEntries.join(
    '\n'
  )}\n} as const;`;
}
