// Auto-generated file - do not edit manually
// Generated by react-native-smart-assets

export type AssetName =
  | 'adaptive-icon'
  | 'favicon'
  | 'icon'
  | 'splash-icon'
  | 'support';

export const ASSETS = {
  'adaptive-icon': require('./adaptive-icon.png'),
  'favicon': require('./favicon.png'),
  'icon': require('./icon.png'),
  'splash-icon': require('./splash-icon.png'),
  'support': require('./support.svg'),
} as const;

export const ASSET_METADATA = {
  'adaptive-icon': {
    name: 'adaptive-icon',
    type: 'image',
    category: 'assets',
  },
  'favicon': {
    name: 'favicon',
    type: 'image',
    category: 'assets',
  },
  'icon': {
    name: 'icon',
    type: 'image',
    category: 'assets',
  },
  'splash-icon': {
    name: 'splash-icon',
    type: 'image',
    category: 'assets',
  },
  'support': {
    name: 'support',
    type: 'svg',
    category: 'assets',
  },
} as const;

export function getAsset(name: AssetName): (typeof ASSETS)[AssetName] {
  return ASSETS[name];
}

export function hasAsset(name: string): name is AssetName {
  return name in ASSETS;
}

export function getAllAssetNames(): AssetName[] {
  return Object.keys(ASSETS) as AssetName[];
}
